name: Kondukto Debug Pipeline
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: hello-world

jobs:
  debug-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install Kondukto CLI
        run: |
          curl -sSL https://cli.kondukto.io | sh
          export PATH=$PATH:/usr/local/bin
      
      - name: Check Environment Variables
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          echo "=== Environment Check ==="
          # Host kontrolü (domain kısmını göster, protokol kısmını gizle)
          echo "KONDUKTO_HOST exists: $(if [ ! -z "$KONDUKTO_HOST" ]; then echo "YES"; else echo "NO"; fi)"
          echo "KONDUKTO_HOST domain: $(echo $KONDUKTO_HOST | cut -d'/' -f3)"
          
          # Token kontrolü (sadece var/yok bilgisi)
          echo "KONDUKTO_TOKEN exists: $(if [ ! -z "$KONDUKTO_TOKEN" ]; then echo "YES"; else echo "NO"; fi)"
          echo "KONDUKTO_TOKEN length: $(echo $KONDUKTO_TOKEN | wc -c)"
          
          # Kondukto CLI version kontrolü
          echo "=== Kondukto CLI Version ==="
          kdt version
          
          echo "=== Testing Connection ==="
          # Basit bir komut ile bağlantıyı test et
          kdt project list
