name: Kondukto Scan with Docker
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: hello-world

jobs:
  kondukto-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-app .

      - name: Run Application
        run: |
          docker run -d -p 3000:3000 my-app

      - name: Check Container Logs
        run: |
          sleep 5
          docker logs $(docker ps -q --filter ancestor=my-app)

      - name: Install Kondukto CLI
        run: |
          curl -sSL https://cli.kondukto.io | sh
          export PATH=$PATH:/usr/local/bin
          kdt version

      - name: Debug Kondukto Project Information
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          echo "=== Debug Information Start ==="
          echo "Checking Kondukto Connection..."
          kdt status
          echo "Listing All Projects..."
          kdt project list --json
          echo "Current Project Name: ${{ env.PROJECT_NAME }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "=== Debug Information End ==="

      - name: Run Gitleaks Scan
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          echo "Attempting scan with PROJECT_NAME..."
          kdt scan -p ${{ env.PROJECT_NAME }} -t gitleaks -b main --debug

      - name: Run Checkmarx AST Scan
        if: success()
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          kdt scan -p ${{ env.PROJECT_NAME }} -t checkmarxast -b main --params=start_scan:true --debug

      - name: Run Checkmarx SCA Scan
        if: success()
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          kdt scan -p ${{ env.PROJECT_NAME }} -t checkmarxastsca -b main --params=start_scan:true --debug

      - name: Run Checkmarx KICS Scan
        if: success()
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          kdt scan -p ${{ env.PROJECT_NAME }} -t checkmarxastkics -b main --params=start_scan:true --debug
