name: Kondukto Scan with Docker
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: kondukto-hello-world  # Kondukto'daki proje adınız

jobs:
  kondukto-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t my-app .

      - name: Run Application
        run: |
          docker run -d -p 3000:3000 my-app

      - name: Check Container Logs
        run: |
          sleep 5  # Konteyner'ın başlaması için kısa bir bekleme
          docker logs $(docker ps -q --filter ancestor=my-app)

      - name: Install Kondukto CLI
        run: |
          curl -sSL https://cli.kondukto.io | sh
          export PATH=$PATH:/usr/local/bin
          # CLI'ın düzgün kurulduğunu kontrol et
          kdt version

      - name: Verify Kondukto Connection
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          # Kondukto bağlantısını test et
          kdt project list

      - name: Run Gitleaks Scan
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          kdt scan -p ${{ env.PROJECT_NAME }} -t gitleaks -b main --debug

      - name: Run Checkmarx AST Scan
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          kdt scan -p ${{ env.PROJECT_NAME }} -t checkmarxast -b main --params=start_scan:true --debug

      - name: Run Checkmarx SCA Scan
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          kdt scan -p ${{ env.PROJECT_NAME }} -t checkmarxastsca -b main --params=start_scan:true --debug

      - name: Run Checkmarx KICS Scan
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          kdt scan -p ${{ env.PROJECT_NAME }} -t checkmarxastkics -b main --params=start_scan:true --debug

      - name: Error Check
        if: failure()
        run: |
          echo "Pipeline failed. Please check the logs above for details."
          exit 1
