name: Kondukto Scan with Docker

on:
  push:
    branches:
      - main

jobs:
  kondukto-scan:
    runs-on: ubuntu-latest

    steps:     
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image     

      run: |
        docker build -t my-app .

    - name: Run Application     
      run: |
        docker run -d -p 3000:3000 my-app

    - name: Check Container Logs    
      run: |
        docker logs $(docker ps -q --filter ancestor=my-app)

    - name: Install Kondukto CLI     
      run: |
        curl -sSL https://cli.kondukto.io | sh
        export PATH=$PATH:/usr/local/bin
        
    - name: Run Gitleaks Scan    # Kondukto Taramas覺 (Gitleaks)
      env:
        KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
        KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
      run: |
        kdt scan -p "Hello-World" -t gitleaks -b main

    - name: Run Checkmarx AST Scan    # Kondukto Taramas覺 (Checkmarx AST)
      env:
        KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
        KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
      run: |
        kdt scan -p "Hello-World" -t checkmarxast -b main --params=start_scan:true --params=project:kondukto-test/kondukto-hello-world

    - name: Run Checkmarx SCA Scan    # Kondukto Taramas覺 (Checkmarx SCA)
      env:
        KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
        KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
      run: |
        kdt scan -p "Hello-World" -t checkmarxastkics -b main --params=start_scan:true --params=project:kondukto-test/kondukto-hello-world

    - name: Run Checkmarx KICS Scan     #  Kondukto Taramas覺 (Checkmarx KICS)
      env:
        KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
        KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
      run: |
        kdt scan -p "Hello-Word" -t checkmarxastsca -b main --params=start_scan:true --params=project:kondukto-test/kondukto-hello-world


