name: Kondukto Integration Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-kondukto-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check KONDUKTO_HOST format and accessibility
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
        run: |
          echo "Debug: Checking KONDUKTO_HOST value..."
          echo "Current KONDUKTO_HOST value: $KONDUKTO_HOST"
          
          if [ -z "$KONDUKTO_HOST" ]; then
            echo "Error: KONDUKTO_HOST is empty or not set"
            exit 1
          fi
          
          # Check if KONDUKTO_HOST starts with https://
          if [[ ! "$KONDUKTO_HOST" =~ ^https:// ]]; then
            echo "KONDUKTO_HOST must start with https://"
            echo "Current value: $KONDUKTO_HOST"
            exit 1
          fi
          
          # Extract domain without protocol
          DOMAIN=$(echo "$KONDUKTO_HOST" | sed 's|^https://||')
          echo "KONDUKTO_HOST domain: $DOMAIN"

      - name: Validate KONDUKTO_TOKEN
        env:
          KONDUKTO_TOKEN: ${{ vars.KONDUKTO_TOKEN }}
        run: |
          if [ -z "$KONDUKTO_TOKEN" ]; then
            echo "Error: KONDUKTO_TOKEN is empty or not set"
            exit 1
          fi
          echo "KONDUKTO_TOKEN exists: YES"
          
          # Check token length using multiple methods
          TOKEN_LENGTH=$(echo -n "$KONDUKTO_TOKEN" | wc -c)
          TOKEN_LENGTH_BASH=${#KONDUKTO_TOKEN}
          
          echo "KONDUKTO_TOKEN length (wc): $TOKEN_LENGTH"
          echo "KONDUKTO_TOKEN length (bash): $TOKEN_LENGTH_BASH"
          
          if [ "$TOKEN_LENGTH" -ne 81 ]; then
            echo "Token length mismatch. Expected 81, got $TOKEN_LENGTH"
            echo "Checking for hidden characters:"
            echo -n "$KONDUKTO_TOKEN" | hexdump -C
            exit 1
          fi

      - name: Summary
        env:
          KONDUKTO_HOST: ${{ vars.KONDUKTO_HOST }}
        run: |
          echo "Integration Check Summary:"
          echo "========================="
          echo "KONDUKTO_HOST: $KONDUKTO_HOST"
          echo "KONDUKTO_TOKEN: [SECURED]"
          echo "All checks passed successfully!"
        if: success()
